platform: linux

image_resource:
  type: docker-image
  source: { repository: busybox }

inputs:
  - name: trivy-version
  - name: golangci-lint-version
outputs:
  - name: build-params

run:
  path: /bin/sh
  args:
    - -ec
    - |
      echo "TRIVY_VERSION=`cat trivy-version/.git/ref`" > build-params/build-params
      echo "GOLANGCI_LINT_VERSION=`cat golangci-lint-version/.git/ref`" >> build-params/build-params
