platform: linux

image_resource:
  type: docker-image
  source: { repository: busybox }

inputs:
  - name: trivy-version
outputs:
  - name: build-params

run:
  path: /bin/sh
  args:
    - -c
    - |
      echo "TRIVY_VERSION=`cat trivy-version/.git/ref`" > build-params/build-params
