platform: linux

image_resource:
  type: registry-image
  source:
    repository: philipsahli/cicd-image

inputs:
  - name: version
    optional: true

params:
  IMAGE: ((IMAGE))
  LIMIT: ((LIMIT))

run:
  path: sh
  args:
    - -exc
    - |
      limit=$LIMIT
      export TRIVY_LIGHT=true
      export TRIVY_QUIET=true

      case $IMAGE in
          *.tar) echo running on an image file
             TARGET="--input $IMAGE"
          ;;
          *) echo running on an image from a registry
             TAG=`cat version/number`
             TARGET="$IMAGE:$TAG"
          ;;
      esac

      v=`trivy image --format template --template '{{- $vulnerabilities := 0 }}{{- range . }}{{- range .Vulnerabilities }}{{- if or (eq .Severity "CRITICAL") (eq .Severity "HIGH") }}{{- $vulnerabilities = add $vulnerabilities 1 }}{{- end }}{{- end }}{{- end }}{{ $vulnerabilities}}' $TARGET`

      if [ $v -gt $limit ]; then
          echo "Vulnerabilities count of $v too high" 
          trivy image $IMAGE
          exit 1
      fi

      echo "$v vulnerabilities is ok (limit of $LIMIT)"
