resources:
  - name: repo-tfe-resource
    type: git
    icon: github
    source:
      uri: git@github.com:orstensemantics/concourse-tfe-resource
      branch: master
      private_key: |
        ((github-key.key))

  - name: ci-image
    type: registry-image
    icon: docker
    source:
      repository: philipsahli/cicd-image
      username: ((docker.username))
      password: ((docker.password))
      tag: 0.11.0

  - name: concourse-tfe-resource-image
    type: registry-image
    icon: docker
    source:
      repository: philipsahli/concourse-tfe-resource
      username: ((docker.username))
      password: ((docker.password))
      tag: latest

  - name: golang-alpine-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      username: ((docker.username))
      password: ((docker.password))
      tag: alpine

  - name: alpine-image
    type: registry-image
    icon: docker
    source:
      repository: alpine
      username: ((docker.username))
      password: ((docker.password))
      tag: latest

  - name: every-120m
    type: time
    icon: clock-outline
    source:
      interval: 120m

jobs:
  - name: build-image-and-push
    plan:
      - get: repo-tfe-resource
      - get: golang-alpine-image
        trigger: true
      - get: alpine-image
        trigger: true
      - task: build-task-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: repo-tfe-resource
          outputs:
            - name: image
          params:
            DOCKERFILE: repo-tfe-resource/Dockerfile
            CONTEXT: repo-tfe-resource
          run:
            path: build
      - put: concourse-tfe-resource-image
        params:
          image: image/image.tar

  - name: scan-tfe-resource
    plan:
      - get: every-120m
        trigger: true
      - get: ci-image
      - get: repo-tfe-resource
      - in_parallel:
          - task: run-trivy
            privileged: true
            input_mapping:
              repo-tfe-resource: repo
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: philipsahli/cicd-image
              run:
                path: sh
                args:
                  - -exc
                  - |
                    trivy image --exit-code 1 philipsahli/concourse-tfe-resource
