resources:
  - name: repo
    type: git
    source:
      uri: git@github.com:sahlinet/cicd-image
      branch: develop
      private_key: |
        ((github-key.key))

  - name: repo-main
    type: git
    source:
      uri: git@github.com:sahlinet/cicd-image
      branch: main
      private_key: |
        ((github-key.key))

  - name: ci-image
    type: registry-image
    icon: docker
    source:
      repository: philipsahli/cicd-image
      username: ((docker.username))
      password: ((docker.password))

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:sahlinet/versions
      initial_version: 0.1.0
      branch: develop
      file: version-ci-image
      private_key: |
        ((github-key.key))

  - name: every-120m
    type: time
    icon: clock-outline
    source:
      interval: 120m

jobs:
  - name: build-scan-and-push
    plan:
      - get: repo-main
      - get: repo
      - get: version
        trigger: true

      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: repo
          outputs:
            - name: image
          params:
            DOCKERFILE: repo/Dockerfile
          run:
            path: build

      - task: scan
        privileged: true
        file: repo/ci/tasks/run-trivy.yaml
        vars:
          IMAGE: image/image.tar
          LIMIT: 10

      - put: ci-image
        params:
          image: image/image.tar
          additional_tags: version/number

      - put: repo-main
        params:
          repository: repo

  - name: scan-cicd-image
    plan:
      - get: every-120m
        trigger: true
      - get: repo
        trigger: true
      - get: version
        trigger: true
        passed: [build-scan-and-push]

      - get: ci-image
      - in_parallel:
          - task: run-trivy
            privileged: true
            file: repo/ci/tasks/run-trivy.yaml
            vars:
              IMAGE: philipsahli/cicd-image
              LIMIT: 10

  - name: release-rc
    plan:
      - get: version
        params: { pre: rc }
      - put: version
        params: { file: version/number }
  - name: release-patch
    plan:
      - get: version
        params: { bump: patch }
      - put: version
        params: { file: version/number }
  - name: release-minor
    plan:
      - get: version
        params: { bump: minor }
      - put: version
        params: { file: version/number }
  - name: release-major
    plan:
      - get: version
        params: { bump: major }
      - put: version
        params: { file: version/number }
