---
resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: git@github.com:sahlinet/cicd-image
      branch: develop
      private_key: |
        ((github-key.key))

  - name: repo-main
    type: git
    icon: github
    source:
      uri: git@github.com:sahlinet/cicd-image
      branch: main
      private_key: |
        ((github-key.key))

  - name: pull-request
    type: pull-request
    icon: source-pull
    source:
      repository: sahlinet/cicd-image
      access_token: ((github-access.token))

  - name: ci-image
    type: registry-image
    icon: docker
    source:
      repository: philipsahli/cicd-image
      tag: 0.13.0
      username: ((docker.username))
      password: ((docker.password))

  - name: version
    type: semver
    icon: tag-outline
    source:
      driver: git
      uri: git@github.com:sahlinet/versions
      initial_version: 0.1.0
      branch: develop
      file: version-ci-image
      private_key: |
        ((github-key.key))

  - name: every-120m
    type: time
    icon: clock-outline
    source:
      interval: 120m

  - name: trivy-version
    type: git
    icon: tag-outline
    source:
      uri: https://github.com/aquasecurity/trivy
      tag_filter: v*[0-9].*[0-9].*[0-9]

jobs:
  - name: build-scan-and-push
    plan:
      - get: repo-main
      - get: repo
      - get: version
        trigger: true
      - get: trivy-version

      - task: fill-versions
        file: repo/ci/tasks/fill-trivy-version.yaml

      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: repo
          outputs:
            - name: image
          params:
            DOCKERFILE: repo/Dockerfile
          run:
            path: build

      - task: scan
        privileged: true
        file: repo/ci/tasks/run-trivy.yaml
        vars:
          IMAGE: image/image.tar
          TAG: ""
          LIMIT: 10

      - put: ci-image
        params:
          image: image/image.tar
          additional_tags: version/number

      - put: repo-main
        params:
          tag: version/number
          force: true
          tag_prefix: "v"
          repository: repo

  - name: scan-cicd-image
    plan:
      - get: every-120m
        trigger: true
      - get: repo
        trigger: true
      - get: version
        trigger: true
        passed: [build-scan-and-push]

      - get: ci-image
      - in_parallel:
          - task: run-trivy
            privileged: true
            file: repo/ci/tasks/run-trivy.yaml
            vars:
              IMAGE: philipsahli/cicd-image
              TAG: ""
              LIMIT: 10

  - name: release-rc
    plan:
      - get: version
        params: { pre: rc }
      - put: version
        params: { file: version/number }
  - name: release-patch
    plan:
      - get: version
        params: { bump: patch }
      - put: version
        params: { file: version/number }
  - name: release-minor
    plan:
      - get: version
        params: { bump: minor }
      - put: version
        params: { file: version/number }
  - name: release-major
    plan:
      - get: version
        params: { bump: major }
      - put: version
        params: { file: version/number }

  - name: pull-requests
    plan:
      - get: pull-request
        trigger: true
        version: every
      - get: trivy-version

      - put: pull-request
        params:
          path: pull-request
          status: pending

      - task: fill-versions
        file: pull-request/ci/tasks/fill-trivy-version.yaml

      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: pull-request
            - name: build-params
          outputs:
            - name: image
          params:
            DOCKERFILE: pull-request/Dockerfile
            BUILD_ARGS_FILE: build-params/build-params
          run:
            path: build
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure

      - put: pull-request
        params:
          path: pull-request
          status: success

resource_types:
  - name: pull-request
    type: registry-image
    source: { repository: teliaoss/github-pr-resource }
